name: GitHub Actions Vercel Develop Deployment
env:
  
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:  
    push:
         
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install --location=global vercel@canary pnpm@8.15.7

    #  - name: Pull Vercel Environment Information
    #    run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
		
      - name: Set up Python
        uses: actions\setup-python@v2
        with:
          python-version: '3.9'  # Replace with your Python version

      - name: Install dependencies
        run: |
         python -m venv env
         source env/bin/activate
         pip install -r requirements.txt

      - name: Run the application
        run: uvicorn main:app --reload

     # - name: Build Project Artifacts
     #   run: vercel build --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set `cat domain.txt` ashok-fastapi.vercel.app
